spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ENC(usctfEPy/RuSl8xQQCQj41tcD0sl+VnVWHwe4qkenlc=)
            client-secret: ENC(WDv60F7EEKX3Ssf5IpwPXKp+NfWRtrU1TTw7Daws1c4maSYp+anV7RFGI22z2RWP)
            #            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            #            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
          #            client-name: Facebook
          naver:
            client-id: ENC(BXKH5s+hy8orrXVeFUcwoQ+iUJJdKKT2Z9pKLS+AL8w=)
            client-secret: ENC(Zf5qFurjVhHLCFTak+2LiRUKPWyWyqHN)
            #            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile
              - email
              - name
            client-name: Naver

          google:
            client-id: ENC(fqWDPN+6uIzNQ8t+WQrSTixQOEyIqqplhgzpmOlxx+tNjBobgTxrbiwvsNS6uL036uVYR1AeIA0ATArA4DJdVE+zLzLVyOVsLPgP/reTrba8kxOvqiGryA==)
            client-secret: ENC(K9IoUVIjMwSSEyWNnipXl0HLSPXY2pC8QGmOTVS07OkQPe2ZJYDiOYFRkx/0U33d)
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#        kakao는 email을 제공하지 않아서 제외 후에 앱 배포후 추가예정. todo

