spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ENC(LJtkayQpTxYiikOEz579DqXOeTjC9oiZKVk4+WUacHqWr2Ra4668FsP+EhzsmCjU)
            client-secret: ENC(edX9jfben1eT3j3P+dndzFMEhwfhil6UG1dz4WOahJD4s2lQNPHahbmZO3t/diJwXmmBrvv8X2f8vG9bIvbRtDx82DFzs/w3ShRtZeDTuIE=)
            #            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            #            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
          #            client-name: Facebook
          naver:
            client-id: ENC(39OOALO8Oe9qmsj3qpTfCbyMac6KI2ZWFc0fmHrkCi5gk/u4pxlf4Bpe840M/+X5FbWusCVAGmjRAY00z15m1g==)
            client-secret: ENC(5bt0exOalhc+hbst060fB2z9RmLriUOSvF89X1j1wLwCOEHxsUcopTRL3rqd4WS4)
            #            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile
              - email
              - name
            client-name: Naver

          google:
            client-id: ENC(PG12lYwQXI1LgMTs0luy+9NWRmLiRyuttLXCXnQPhp+20QPTXClrdSvm4N9+UE0tPLAF5ndLtXFt6nlGjreXfvEERfkbrhlauXsmXyN8Z+ZV9DC2MSzIIWXV/MEHhS3z62tDiHJLP7rXF8fBS7QALA==)
            client-secret: ENC(Uogb6QW8YMTWWklPmVXfY+0kML2/TCRhLZ/+PjPiNRQrSTWtrRYwR2pdRAriELQh3psGyuriHsSHYd/BKwtI1wE6OAznPPqGGTFZ47ohJKM=)
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#        kakao는 email을 제공하지 않아서 제외 후에 앱 배포후 추가예정. todo

