spring:
  email:
    host: smtp.gmail.com
    port: 587
    username: ENC(ym8UQk6RseIVbRWoNXxvw96y3dfd2OuZkWt0TGUzVgDFBVY8Eah/J0pAyVHxHPKmQLFJrtvJUvErWU5sRdI+oQ==)
    password: ENC(0gC97VXAEGx6EXq2LzsgAGrlzsEmK1Vbqn4gPrwjD8HzmhRsQXV+uf9vvoLVBqrkxdMgorpXFlrv7VS7pzzQ/g==)
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
    auth-code-expiration-mills: 600000 #10분
  liquibase:
    change-log: db/db.changelog-main.yml
  jpa:
    properties:
      hibernate:
        ddl-auto: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jakarta:
          persistence:
            query:
              timeout: 5000
  graphql:
    graphiql:
      enabled: true
    schema:
      file-extensions: .gql
      locations: classpath*:graphql/**/
      printer:
        enabled: true
  #  servlet:
  #    multipart:
  #      # location: c:\\Temp\\upload
  #      maxFileSize: 10MB
  #      maxRequestSize: 10MB
  datasource:
    hikari:
      leak-detection-threshold: 20000
  #  boot:
  #    admin:
  #      client:
  #        url: https://main.spring-boot.smartdoctor.systems
  #        instance:
  #          service-host-type: ip
  mvc:
    log-request-details: true
    log-resolved-exception: true
  profiles:
    include:
      - oauth2
  error:
    include-message: always
    include-stacktrace: never
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
